name: Build
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "9.8"
          - "9.10"
          - "9.12"
        include:
          - os: macOS-latest
            ghc: "9.12"
          - os: windows-latest
            ghc: "9.12"
    steps:
    - uses: actions/checkout@v5

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"
        cabal-update: true

    - uses: actions/cache@v4
      name: Cache cabal store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Cabal version
      run: |
        cabal --version

    - name: Unpack
      run: |
        cabal sdist --ignore-project --output-directory ..
        cd ..
        cabal get emacs-native-*.tar.gz

    - name: Build
      run: |
        cd ../emacs-native-*/
        cabal build all --enable-tests --enable-benchmarks

    - name: Test
      run: |
        cd ../emacs-native-*/
        cp -r ../emacs-native/test-data .
        cabal run emacs-native:test:emacs-native-test -- --quickcheck-tests=100000 --quickcheck-max-size=1000

  emulated:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ['armv7', 'aarch64']
    steps:
    - uses: actions/checkout@v5

    - uses: actions/cache@v4
      name: Cache cabal store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-arm-${{ matrix.arch }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-arm-${{ matrix.arch }}-

    - uses: uraimo/run-on-arch-action@v3
      with:
        arch: ${{ matrix.arch }}
        distro: ubuntu_rolling
        githubToken: ${{ github.token }}
        install: |
          apt-get update -y
          apt-get install -y curl ghc cabal-install libghc-tasty-quickcheck-dev libghc-tasty-hunit-dev g++
        run: |
          cabal update

          cabal build --enable-tests --enable-benchmarks all

          cabal run emacs-native:test:emacs-native-test -- --quickcheck-tests=10000 --quickcheck-max-size=256 --ansi-tricks=false
